checksumBehavior: update

packageExtensions:
  "jscpd@*":
    dependencies:
      "@jscpd/leveldb-store": "*"
  "@jscpd/html-reporter@*":
    dependencies:
      "@jscpd/finder": "*"
  wo-library@*:
    dependencies:
      "@storybook/addon-styling-webpack": "*"

yarnPath: .yarn/releases/yarn-4.2.2.cjs
