checksumBehavior: update

packageExtensions:
  "@chromatic-com/storybook@1.3.2":
    dependencies:
      "@storybook/core-events": "*"
  eslint-plugin-perfectionist@2.8.0:
    dependencies:
      "@typescript-eslint/types": "*"
  wo-library@*:
    dependencies:
      "@storybook/addon-styling-webpack": "*"

yarnPath: .yarn/releases/yarn-4.2.2.cjs
