checksumBehavior: update

packageExtensions:
  "@jscpd/html-reporter@*":
    dependencies:
      "@jscpd/finder": "*"
  jscpd@*:
    dependencies:
      "@jscpd/leveldb-store": "*"
  wo-library@*:
    dependencies:
      "@storybook/addon-styling-webpack": "*"

yarnPath: .yarn/releases/yarn-4.3.0.cjs
