checksumBehavior: update

yarnPath: .yarn/releases/yarn-4.1.1.cjs

packageExtensions:
  wo-library@*:
    dependencies:
      "@storybook/addon-styling-webpack": "*"
  "eslint-plugin-perfectionist@2.8.0":
    dependencies:
      "@typescript-eslint/types": "*"
  "@chromatic-com/storybook@1.3.2":
    dependencies:
      "@storybook/core-events": "*"
