# Workflow name
name: "Lint Checks"

on:
  pull_request:
  push:
    branches:
      - main
      - 1.x
      - 2.x

jobs:
  lint-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 18
      - run: yarn set version berry
      - run: yarn
      - run: yarn eslint --quiet src
      - run: yarn stylelint ./src/**/*.css
      - run: yarn prettier --check src
      - run: yarn jscpd src
