name: "Lint"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tiwariav/github-actions/setup-yarn@main
      - run: yarn eslint --quiet src
      - run: yarn stylelint ./src/**/*.css
      - run: yarn prettier --check src
      - run: yarn jscpd src
